### ISSUE TITLE
One or more environment variables failed assertions

### ISSUE THREAD

**Issue by OnkelTem** [johnpbloch/wordpress-project#5]
I was not sure where should I ask this question, so I opted to that issue queue:

https://github.com/vlucas/phpdotenv/issues/524

**Comment by reneroboter** [comment]
You must load the dotenvs with `$dotenv->load();` 🙂

**Edit**: Sorry, I don't the that the answer was already given in https://github.com/vlucas/phpdotenv/issues/524

**Comment by johnpbloch** [comment]
Fixed in #6
